name: Build Website

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".*/**"
      - ".*"
      - "!.well-known/**"
      - "!.jekyll.yml"
      - "!.tool-versions"
      - "bin/**"
      - "LICENSE*"
      - "SUPPORT.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".*/**"
      - ".*"
      - "!.well-known/**"
      - "!.jekyll.yml"
      - "!.tool-versions"
      - "bin/**"
      - "LICENSE*"
      - "SUPPORT.md"
  workflow_dispatch: {}

jobs:
  main:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7.0.0

      - name: Setup Ruby
        env:
          BUNDLE_SPECIFIC_PLATFORM: 1
        uses: ruby/setup-ruby@v1.316.0
        with:
          bundler-cache: true

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --config .jekyll.yml

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

  deploy:
    needs: main
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
